title: Qingshuang # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    <br><br>
  Statistics and Data Science student with industry research experience. Combines quantitative analysis and qualitative insights to understand real-world problems and translate findings for diverse audiences.
  <br><br>
  <a href="https://www.linkedin.com/in/qingshuang-xie-72170a355/?skipRedirect=true">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
